name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  http: ^1.3.0
  provider: ^6.0.2
  flutter_bloc: ^9.1.0
  flutter_tts: ^4.2.2
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.5
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.20.2
  equatable: ^2.0.5
  get_it: ^8.0.3
  weather: ^3.1.1
  geolocator: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
